/* This is the first program I write in js 
It is a classic game of Rock Paper Scissors 
let assimilate  Rock by number 1, Paper is 2 et Scissors is 3
let getRandomNum to get a random number between 1 and 3. this number represents computerChoice 
let getComputerSelection a function to translate the random returned number from getRandomNum to a choice. 
let playRound a function that prompt to the user the selection 
*/ 

function getRandomNum (min, max) {      //This function is to get a random number between min and max 
    const floatRandom = Math.random();
    const difference = max - min;

    const random = Math.round(floatRandom * difference);
    const randomWithinRange = random + min;
    return randomWithinRange;
}

function getComputerSelection() {   //this function takes a random number generated by getRandomNum between 1 and 3 and return the choice it corresponds
    let computerChoiceNum = getRandomNum(1,3);
    let computerChoice;
    console.log("Computer choice number :", computerChoiceNum);
    switch (computerChoiceNum) {
        case 1:
            computerChoice = "rock";
            break;
        case 2:
            computerChoice = "paper";
            break;
        case 3:
            computerChoice = "scissors";
    }
    return computerChoice;
}

function getPlayerSelection() {     //This function return the player selection, it verifies if the input is correct and return itr, otherwise it loops until right input
    let playerSelection = prompt("choose Rock, Paper or Scissors :");
    let rightChoice = ["rock", "paper", "scissors"];
    if (playerSelection == null) {
        return null;
    }
    while (!(rightChoice.includes(playerSelection))) {
        playerSelection = prompt("Wrong selection, you have to choose rock, paper or scissors : ")
    }
    return playerSelection;
}

function playRound(playerSelection, computerSelection) {    //This function is set to play a round and return message outputted to user, round score (win, draw or lose)
    let roundScoreString;
    let roundScore;
    let roundDraw = 0;
    if (playerSelection.toLocaleLowerCase() === computerSelection.toLocaleLowerCase()) {
        roundScoreString = `No winner, you both ${playerSelection}`
        roundDraw = 1;
    } else { 
        if (playerSelection.toLocaleLowerCase() === "rock") {
            switch (computerSelection.toLocaleLowerCase()) {
                case "paper":
                    roundScoreString = `You have lost, paper beats rock`;
                    roundScore = 0;
                    break;
                case "scissors":  
                    roundScoreString = "You have won, rock beats scissors";
                    roundScore = 1;
            }
        } else if (playerSelection.toLocaleLowerCase() === "paper") {
            switch (computerSelection.toLocaleLowerCase()) {
                case "rock":
                    roundScoreString = `You have won, paper beats rock`;
                    roundScore = 1;
                    break;
                case "scissors":  
                    roundScoreString = "You have lost, scissors beats paper";
                    roundScore = 0;
            }
        } else if (playerSelection.toLocaleLowerCase() === "scissors") {
            switch (computerSelection.toLocaleLowerCase()) {
            case "rock":
                roundScoreString = `You have lost, rock beats scissors`;
                roundScore = 0;
                break;
            case "paper":  
                roundScoreString = "You have won, scissors beats paper";
                roundScore = 1;
            }
        } else {
            roundScoreString = "Wrong input, make a choice : Rock, Paper or Scissors !"
        }
    }
    return [roundScoreString, roundScore, roundDraw];
}

function finalResult(computerScore, playerScore) {      //This function return the final message to user "Win or lose" depending on the score of the game
    let finalResult;
    if (computerScore > playerScore) {
        finalResult = "You have lost the game vs computer! \nHard Luck !";
    } else if (computerScore < playerScore) {    // Note that we are player best of 5 round, there is no chance of a draw in our case. if number of rounds is pair change this condition. 
        finalResult = "You have won the game vs computer !\nCongrats !!!";
    } else {
        finalResult = "It's a draw !"
    }
    return finalResult;
}


function playGame() {   //this function is to play a game of 5 rounds
    let playerScore = 0;
    let computerScore = 0;
    let draw = 0;
    while (playerScore + computerScore + draw < 5) {      //To modify it by playerScore + computerScore <= 5
        const playerSelection = getPlayerSelection();
        console.log(playerSelection);
        if (playerSelection === null) {
            console.log("You have exited the game.");
            break; //To exit the loop when the player press cancel button
        } else {
            const ComputerSelection = getComputerSelection(); 
            const results = playRound(playerSelection, ComputerSelection);
            const roundResult = results[0];
            if (results[1]) {
                playerScore += 1;
            } else if (!results[1] && !results[2]) {
                computerScore += 1;
            }
            draw += results[2];
            console.log(`You have chosen ${playerSelection}`);
            console.log(`Computer have chosen ${ComputerSelection}`);
            console.log(roundResult);
            console.log(`Score of the game : \nComputer : ${computerScore} \nPlayer : ${playerScore} \nDraws : ${draw}`)
        }
    }
    console.log(finalResult(computerScore, playerScore)); // This works in our case (5 rounds), if number of round is pair make changes in code of the function to take in count the case of draws. 
}

playGame();

